"""Integration tests for rosetta_squint.

Each algorithm is tested in three ways:
1. Path input returns a non-empty ImageHash
2. Path input == bytes input (both produce same hex)
3. Squint output == calling rosetta_imagehash directly on the decoded
   PIL.Image (chain consistency — no surprise transformations)

We do NOT compare against `hash/spec/goldens.json` directly because those
goldens were generated by PIL.Image.open() which is exactly what
rosetta_squint uses for non-HEIC formats. So spec/goldens.json values
*should* match rosetta_squint output for PNG/JPEG fixtures — we assert
this where it adds confidence.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

import rosetta_squint as rs

# Fixtures from the hash side of the merged repo.
# tests/test_squint.py → tests/ → python/ → squint/ → rosetta-squint/
REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent
HASH_FIXTURES = REPO_ROOT / "hash" / "spec" / "fixtures"
HASH_GOLDENS = REPO_ROOT / "hash" / "spec" / "goldens.json"
DECODE_FIXTURES = REPO_ROOT / "decode" / "spec" / "fixtures"

PNG_FIXTURE = HASH_FIXTURES / "imagehash.png"
PEPPERS = HASH_FIXTURES / "peppers.png"
JPEG_FIXTURE = DECODE_FIXTURES / "jpeg" / "valid" / "8x8-grayscale.jpg"


def _read(path: Path) -> bytes:
    return path.read_bytes()


# Sanity: fixtures exist where we expect them.
def test_fixtures_exist():
    assert PNG_FIXTURE.exists(), f"missing {PNG_FIXTURE}"
    assert PEPPERS.exists(), f"missing {PEPPERS}"
    assert JPEG_FIXTURE.exists(), f"missing {JPEG_FIXTURE}"


# Path/bytes parity for all 10 algorithms.

@pytest.mark.parametrize(
    "algo,size_arg,fixture",
    [
        ("phash", 8, PEPPERS),
        ("phash", 16, PEPPERS),
        ("phash_simple", 8, PEPPERS),
        ("dhash", 8, PEPPERS),
        ("dhash_vertical", 8, PEPPERS),
        ("average_hash", 8, PEPPERS),
        ("whash_haar", 8, PEPPERS),
        ("whash_db4", 8, PEPPERS),
        ("whash_db4_robust", 8, PEPPERS),
        # colorhash takes binbits, default 3
        ("colorhash", 3, PEPPERS),
        # JPEG path through whole pipeline including libjpeg-turbo via PIL
        ("phash", 8, JPEG_FIXTURE),
        ("dhash", 8, JPEG_FIXTURE),
    ],
)
def test_path_equals_bytes(algo: str, size_arg: int, fixture: Path):
    """path and bytes entry points produce identical hex."""
    fn_path = getattr(rs, algo)
    fn_bytes = getattr(rs, f"{algo}_bytes")
    # colorhash uses positional binbits, others use hash_size — both accept positional int
    h1 = fn_path(fixture, size_arg)
    h2 = fn_bytes(_read(fixture), size_arg)
    assert str(h1) == str(h2), (
        f"{algo} {fixture.name} size={size_arg}: path={h1} bytes={h2}"
    )


def test_crop_resistant_hash_path_equals_bytes():
    """crop_resistant_hash has no size param; check path/bytes parity."""
    h_path = rs.crop_resistant_hash(PEPPERS)
    h_bytes = rs.crop_resistant_hash_bytes(_read(PEPPERS))
    assert str(h_path) == str(h_bytes)


# Chain consistency: rs.phash(path) == imagehash.phash(rs.decode_file(path)).

def test_phash_chain_consistency():
    import imagehash
    img = rs.decode_file(PEPPERS)
    h_chain = imagehash.phash(img, hash_size=8)
    h_squint = rs.phash(PEPPERS, 8)
    assert str(h_chain) == str(h_squint)


def test_phash_simple_chain_consistency():
    import imagehash
    img = rs.decode_file(PEPPERS)
    h_chain = imagehash.phash_simple(img, hash_size=8)
    h_squint = rs.phash_simple(PEPPERS, 8)
    assert str(h_chain) == str(h_squint)


def test_dhash_chain_consistency():
    import imagehash
    img = rs.decode_file(PEPPERS)
    h_chain = imagehash.dhash(img, hash_size=8)
    h_squint = rs.dhash(PEPPERS, 8)
    assert str(h_chain) == str(h_squint)


def test_average_hash_chain_consistency():
    import imagehash
    img = rs.decode_file(PEPPERS)
    h_chain = imagehash.average_hash(img, hash_size=8)
    h_squint = rs.average_hash(PEPPERS, 8)
    assert str(h_chain) == str(h_squint)


def test_crop_resistant_hash_chain_consistency():
    import imagehash
    img = rs.decode_file(PEPPERS)
    h_chain = imagehash.crop_resistant_hash(img)
    h_squint = rs.crop_resistant_hash(PEPPERS)
    assert str(h_chain) == str(h_squint)


# Sanity that the hex format is what we expect.
def test_phash_returns_16_hex_chars_for_size_8():
    h = rs.phash(PEPPERS, 8)
    assert len(str(h)) == 16
    assert all(c in "0123456789abcdef" for c in str(h))


# Cross-port live verification: confirm that phash("imagehash.png", 8) yields
# the same hex string that the Go/Java/JS squint ports report (ba8c84536bd3c366).
def test_phash_imagehash_png_matches_other_ports():
    h = rs.phash(PNG_FIXTURE, 8)
    # This was reported by Go, Java, and JS squint implementations.
    assert str(h) == "ba8c84536bd3c366", (
        f"Python rosetta_squint diverged from Go/Java/JS for phash on imagehash.png. "
        f"Python: {h}, others: ba8c84536bd3c366"
    )


def test_crop_resistant_hash_returns_imagemultihash():
    h = rs.crop_resistant_hash(PEPPERS)
    assert hasattr(h, "segment_hashes")
    # Distance to self must be float, not int.
    d = h - h
    assert isinstance(d, float)
    assert d == 0.0


def test_hex_to_multihash_roundtrip():
    mh = rs.crop_resistant_hash(PEPPERS)
    s = str(mh)
    restored = rs.hex_to_multihash(s)
    assert str(restored) == s


# ─── HEIC tests — exercise the ctypes-around-system-libheif bridge ──────────
#
# rosetta_squint decodes HEIC via a ctypes wrapper around system libheif
# (instead of pillow-heif), because pillow-heif bundles libheif 1.21.2 and
# diverges ±1 px from the system libheif 1.17.6 that the 5 native ports link
# to. These tests confirm:
#   (a) HEIC happy-path: decode and hash succeed
#   (b) HEIC alpha handling: RGBA fixture decodes as RGBA
#   (c) HEIC negative paths: malformed/AVIF inputs raise rather than panic
#
# The HEIC bridge has historically been the largest ctypes-FFI surface in
# the project — these tests guard against regressions in the HeifError
# struct handling, handle ownership, plane stride trust, etc. (S-M3, S-M4).

HEIC_RGB = DECODE_FIXTURES / "heic" / "valid" / "16x16.heic"
HEIC_RGBA = DECODE_FIXTURES / "heic" / "valid" / "16x16-rgba.heic"
HEIC_LOSSLESS = DECODE_FIXTURES / "heic" / "valid" / "16x16-lossless.heic"
HEIC_AVIF = DECODE_FIXTURES / "heic" / "invalid" / "avif.heic"
HEIC_BAD = DECODE_FIXTURES / "heic" / "invalid" / "bad-magic.heic"
HEIC_TRUNCATED = DECODE_FIXTURES / "heic" / "invalid" / "truncated.heic"


def _maybe_skip_heic():
    """Skip the HEIC tests cleanly if libheif isn't installed at all."""
    try:
        from rosetta_squint._impl import _load_libheif_xplat
        _load_libheif_xplat()
    except OSError as e:
        pytest.skip(f"system libheif unavailable — skipping HEIC tests: {e}")


def test_heic_decode_rgb_hashes_successfully():
    _maybe_skip_heic()
    if not HEIC_RGB.exists():
        pytest.skip(f"missing fixture {HEIC_RGB}")
    h = rs.phash(HEIC_RGB, 8)
    # phash output is always 16 lowercase hex chars
    assert len(str(h)) == 16
    assert all(c in "0123456789abcdef" for c in str(h))


def test_heic_path_equals_bytes():
    """HEIC must round-trip through path and bytes APIs identically."""
    _maybe_skip_heic()
    if not HEIC_RGB.exists():
        pytest.skip(f"missing fixture {HEIC_RGB}")
    h_path = rs.phash(HEIC_RGB, 8)
    h_bytes = rs.phash_bytes(HEIC_RGB.read_bytes(), 8)
    assert str(h_path) == str(h_bytes)


def test_heic_rgba_decodes():
    """RGBA HEIC must decode cleanly — exercises has_alpha_channel + RGBA chroma path."""
    _maybe_skip_heic()
    if not HEIC_RGBA.exists():
        pytest.skip(f"missing fixture {HEIC_RGBA}")
    # Decode independently to verify mode/dimensions; then hash via squint.
    img = rs.decode_file(HEIC_RGBA)
    assert img.mode in ("RGB", "RGBA")
    assert img.size == (16, 16)
    h = rs.dhash(HEIC_RGBA, 8)
    assert len(str(h)) == 16


def test_heic_lossless_decodes():
    """Lossless HEIC must decode cleanly."""
    _maybe_skip_heic()
    if not HEIC_LOSSLESS.exists():
        pytest.skip(f"missing fixture {HEIC_LOSSLESS}")
    h = rs.average_hash(HEIC_LOSSLESS, 8)
    assert len(str(h)) == 16


def test_heic_invalid_avif_raises():
    """AVIF brand inside a HEIC ftyp is intentionally unsupported in v1."""
    _maybe_skip_heic()
    if not HEIC_AVIF.exists():
        pytest.skip(f"missing fixture {HEIC_AVIF}")
    with pytest.raises(Exception):  # noqa: BLE001 — any exception is acceptable
        rs.phash(HEIC_AVIF, 8)


def test_heic_invalid_bad_magic_raises():
    """A file whose ftyp brand isn't in the HEIC family must fail."""
    _maybe_skip_heic()
    if not HEIC_BAD.exists():
        pytest.skip(f"missing fixture {HEIC_BAD}")
    with pytest.raises(Exception):  # noqa: BLE001
        rs.phash(HEIC_BAD, 8)


def test_heic_invalid_truncated_raises():
    """A truncated HEIC must surface a libheif diagnostic, not silently produce garbage."""
    _maybe_skip_heic()
    if not HEIC_TRUNCATED.exists():
        pytest.skip(f"missing fixture {HEIC_TRUNCATED}")
    with pytest.raises(Exception):  # noqa: BLE001
        rs.phash(HEIC_TRUNCATED, 8)
