"""Generates Group-1 reference vectors that ports compare against.

Each output file is generated by running the actual PIL / scipy / pywt
operation on hand-picked inputs. The contents become the byte-exact
reference that every port's Group-1 unit test reads.

Run:
  python gen_unit_cases.py          # write outputs
  python gen_unit_cases.py --check  # exit 1 on drift
"""
from __future__ import annotations

import argparse
import json
import struct
import sys
import tempfile
from pathlib import Path

import numpy as np
import pywt
import scipy.fftpack as sfp
from PIL import Image

SPEC_DIR = Path(__file__).parent
GRAYSCALE_PATH = SPEC_DIR / "grayscale_cases.json"
HSV_PATH = SPEC_DIR / "hsv_cases.json"
DCT_PATH = SPEC_DIR / "dct_cases.json"
HAAR_PATH = SPEC_DIR / "haar_cases.json"
LANCZOS_DIR = SPEC_DIR / "lanczos_cases"


def gen_grayscale_cases() -> dict:
    """30 RGB triples chosen to stress rounding and channel-extrema."""
    triples = [
        (0, 0, 0), (255, 255, 255), (128, 128, 128),
        (255, 0, 0), (0, 255, 0), (0, 0, 255),
        (1, 1, 1), (254, 254, 254),
        (100, 150, 200), (200, 150, 100),
        (50, 50, 50), (200, 200, 200),
        (32, 32, 32), (85, 85, 85), (170, 170, 170),
        # Random with fixed seed
    ]
    rng = np.random.default_rng(seed=20260519)
    triples += [tuple(int(x) for x in rng.integers(0, 256, size=3)) for _ in range(15)]

    cases = []
    for (r, g, b) in triples:
        img = Image.new("RGB", (1, 1), (r, g, b))
        l = img.convert("L").getpixel((0, 0))
        cases.append({"rgb": [r, g, b], "L": l})
    return {"description": "RGB -> PIL 'L' (grayscale) reference table.",
            "formula_python": "L = (R*19595 + G*38470 + B*7471 + 32768) >> 16",
            "cases": cases}


def gen_hsv_cases() -> dict:
    """30 RGB triples chosen to expose the round-vs-truncate divergence on .5 boundaries."""
    triples = [
        (0, 0, 0), (255, 255, 255), (128, 128, 128),
        (255, 0, 0), (0, 255, 0), (0, 0, 255),
        (255, 255, 0), (0, 255, 255), (255, 0, 255),
        # Known .5-boundary triples (round would give different values than PIL):
        (100, 150, 200),    # PIL: (148, 127, 200); round-naive: (149, 128, 200)
        (0, 255, 255),      # H = 0.5*255 = 127.5  ->  PIL 127 (floor), round 128
        # Boundary fixtures we already built
        (255, 85, 85),      # S = 170 exactly
        (255, 170, 170),    # S = 85 exactly
        (32, 32, 32),       # L = 32 exactly, S=0
    ]
    rng = np.random.default_rng(seed=20260519)
    triples += [tuple(int(x) for x in rng.integers(0, 256, size=3)) for _ in range(17)]

    cases = []
    for (r, g, b) in triples:
        img = Image.new("RGB", (1, 1), (r, g, b))
        h, s, v = img.convert("HSV").getpixel((0, 0))
        cases.append({"rgb": [r, g, b], "hsv": [h, s, v]})
    return {"description": "RGB -> PIL 'HSV' uint8 channels. PIL uses INTEGER arithmetic; Math.round(float_hsv * 255) differs on .5 boundaries.",
            "boundary_examples_to_verify": [
                {"rgb": [100, 150, 200], "pil_hsv": [148, 127, 200], "naive_round": [149, 128, 200]}
            ],
            "cases": cases}


def gen_dct_cases() -> dict:
    """1-D DCT-II type 2, norm=None reference for N=32 on three inputs."""
    inputs = {
        "arange":   list(range(32)),
        "impulse":  [1] + [0] * 31,
    }
    rng = np.random.default_rng(seed=20260519)
    inputs["random_seeded"] = [float(x) for x in rng.normal(loc=128.0, scale=40.0, size=32)]

    cases = {}
    for name, x in inputs.items():
        x_arr = np.asarray(x, dtype=np.float64)
        y = sfp.dct(x_arr, type=2, norm=None)
        cases[name] = {"input": x, "output": [float(v) for v in y]}
    return {"description": "scipy.fftpack.dct(x, type=2, norm=None) for N=32. Tolerance: max abs diff < 1e-9.",
            "n": 32,
            "cases": cases}


def gen_haar_cases() -> dict:
    """Haar wavelet decomposition with 'symmetric' boundary mode on a known 16x16 float input.

    Spec-relevant outputs:
      - single-level decomposition: LL, LH, HL, HH at level 1
      - multi-level (level=4) decomposition: coeffs[0] (LL_4) shape (1,1)
      - reconstruction matches input exactly
    """
    rng = np.random.default_rng(seed=20260519)
    x = rng.normal(loc=0.5, scale=0.2, size=(16, 16))
    x = np.clip(x, 0.0, 1.0)

    # Single level
    cA, (cH, cV, cD) = pywt.dwt2(x, "haar", mode="symmetric")

    # Multi-level full decomposition: level=4 -> coeffs[0] is shape (1,1)
    coeffs = pywt.wavedec2(x, "haar", level=4, mode="symmetric")
    multi_cA = coeffs[0]  # shape (1,1)
    multi_details = [
        [d.tolist() for d in level_tuple] for level_tuple in coeffs[1:]
    ]

    # Reconstruction roundtrip
    reconstructed = pywt.waverec2(coeffs, "haar", mode="symmetric")

    return {
        "description": "Haar DWT with 'symmetric' boundary mode on a 16x16 float64 array (clipped to [0,1]).",
        "input": x.tolist(),
        "single_level": {
            "cA": cA.tolist(), "cH": cH.tolist(), "cV": cV.tolist(), "cD": cD.tolist(),
        },
        "multi_level_4": {
            "cA": multi_cA.tolist(),
            "details_per_level_outer_to_inner": multi_details,
            "reconstructed": reconstructed.tolist(),
        },
        "tolerance": "max abs diff < 1e-12 against pywt; reconstruction within 1e-12 of input"
    }


def _write_lanczos_case(name: str, src: np.ndarray, dst_size: tuple[int, int]) -> dict:
    """Write a single Lanczos test case: input + output as raw bytes; entry for MANIFEST."""
    src_img = Image.fromarray(src.astype(np.uint8), mode="L")
    dst_img = src_img.resize(dst_size, Image.Resampling.LANCZOS)
    dst_arr = np.asarray(dst_img, dtype=np.uint8)
    out_path = LANCZOS_DIR / f"{name}.bin"
    src_h, src_w = src.shape
    dst_w, dst_h = dst_size
    with open(out_path, "wb") as fh:
        fh.write(struct.pack("<IIII", src_w, src_h, dst_w, dst_h))
        fh.write(src.astype(np.uint8).tobytes())
        fh.write(dst_arr.tobytes())
    return {
        "name": name,
        "file": f"lanczos_cases/{name}.bin",
        "src_size": [src_w, src_h],
        "dst_size": [dst_w, dst_h],
        "header_format": "uint32 LE: src_w, src_h, dst_w, dst_h",
        "body_format":   "uint8 array of src_w*src_h, then uint8 array of dst_w*dst_h, row-major",
    }


def gen_lanczos_cases() -> dict:
    """Lanczos reference vectors. Each case captures (input uint8 buffer, output uint8 buffer)
    after PIL's LANCZOS resize on an 'L'-mode image. Format described in MANIFEST.json.
    """
    LANCZOS_DIR.mkdir(exist_ok=True)
    rng = np.random.default_rng(seed=20260519)

    cases = []
    # 64 -> 32 horizontal gradient (the case where float reference diverges from PIL)
    grad = np.tile(np.linspace(0, 255, 64, dtype=np.uint8), (64, 1))
    cases.append(_write_lanczos_case("downsample_64_to_32_gradient", grad, (32, 32)))

    # 16 -> 32 horizontal gradient (upsample, no kernel widening)
    grad_small = np.tile(np.linspace(0, 255, 16, dtype=np.uint8), (16, 1))
    cases.append(_write_lanczos_case("upsample_16_to_32_gradient", grad_small, (32, 32)))

    # 32 -> 32 random uint8 (identity scale; kernel = max(1,1) = 1)
    rand32 = rng.integers(0, 256, size=(32, 32), dtype=np.uint16).astype(np.uint8)
    cases.append(_write_lanczos_case("identity_32_to_32_random", rand32, (32, 32)))

    # 64x48 -> 32x24 asymmetric scale; stresses (W,H) handling
    grad_asym = np.tile(np.linspace(0, 255, 64, dtype=np.uint8), (48, 1))
    cases.append(_write_lanczos_case("asymmetric_64x48_to_32x24", grad_asym, (32, 24)))

    manifest_path = LANCZOS_DIR / "MANIFEST.json"
    manifest = {
        "description": "Lanczos resize reference cases. Each .bin contains a (src_w, src_h, dst_w, dst_h) uint32_le header, then the src uint8 buffer (row-major, grayscale), then the dst uint8 buffer.",
        "pil_version_note": "Produced with Pillow 10.4.0 LANCZOS filter on 'L'-mode images.",
        "cases": cases,
    }
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    return manifest


GENERATORS = {
    "grayscale_cases.json":         gen_grayscale_cases,
    "hsv_cases.json":               gen_hsv_cases,
    "dct_cases.json":               gen_dct_cases,
    "haar_cases.json":              gen_haar_cases,
    "lanczos_cases/MANIFEST.json":  gen_lanczos_cases,
}


def atomic_write_json(path: Path, data: dict) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")
    tmp.replace(path)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    if args.check:
        with tempfile.TemporaryDirectory():
            drift = []
            for name, gen in GENERATORS.items():
                generated = gen()
                committed = json.loads((SPEC_DIR / name).read_text())
                if committed != generated:
                    drift.append(name)
            if drift:
                print("Drift in unit cases:", drift, file=sys.stderr)
                return 1
        print("unit cases: no drift.")
        return 0

    for name, gen in GENERATORS.items():
        atomic_write_json(SPEC_DIR / name, gen())
        print(f"wrote {name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
