"""Generates Group-1 reference vectors that ports compare against.

Each output file is generated by running the actual PIL / scipy / pywt
operation on hand-picked inputs. The contents become the byte-exact
reference that every port's Group-1 unit test reads.

Run:
  python gen_unit_cases.py          # write outputs
  python gen_unit_cases.py --check  # exit 1 on drift
"""
from __future__ import annotations

import argparse
import json
import struct
import sys
import tempfile
from pathlib import Path

import numpy as np
import pywt
import scipy.fftpack as sfp
from PIL import Image

SPEC_DIR = Path(__file__).parent
GRAYSCALE_PATH = SPEC_DIR / "grayscale_cases.json"
HSV_PATH = SPEC_DIR / "hsv_cases.json"
DCT_PATH = SPEC_DIR / "dct_cases.json"
HAAR_PATH = SPEC_DIR / "haar_cases.json"
LANCZOS_DIR = SPEC_DIR / "lanczos_cases"


def gen_grayscale_cases() -> dict:
    """30 RGB triples chosen to stress rounding and channel-extrema."""
    triples = [
        (0, 0, 0), (255, 255, 255), (128, 128, 128),
        (255, 0, 0), (0, 255, 0), (0, 0, 255),
        (1, 1, 1), (254, 254, 254),
        (100, 150, 200), (200, 150, 100),
        (50, 50, 50), (200, 200, 200),
        (32, 32, 32), (85, 85, 85), (170, 170, 170),
        # Random with fixed seed
    ]
    rng = np.random.default_rng(seed=20260519)
    triples += [tuple(int(x) for x in rng.integers(0, 256, size=3)) for _ in range(15)]

    cases = []
    for (r, g, b) in triples:
        img = Image.new("RGB", (1, 1), (r, g, b))
        l = img.convert("L").getpixel((0, 0))
        cases.append({"rgb": [r, g, b], "L": l})
    return {"description": "RGB -> PIL 'L' (grayscale) reference table.",
            "formula_python": "L = (R*19595 + G*38470 + B*7471 + 32768) >> 16",
            "cases": cases}


def gen_hsv_cases() -> dict:
    """30 RGB triples chosen to expose the round-vs-truncate divergence on .5 boundaries."""
    triples = [
        (0, 0, 0), (255, 255, 255), (128, 128, 128),
        (255, 0, 0), (0, 255, 0), (0, 0, 255),
        (255, 255, 0), (0, 255, 255), (255, 0, 255),
        # Known .5-boundary triples (round would give different values than PIL):
        (100, 150, 200),    # PIL: (148, 127, 200); round-naive: (149, 128, 200)
        (0, 255, 255),      # H = 0.5*255 = 127.5  ->  PIL 127 (floor), round 128
        # Boundary fixtures we already built
        (255, 85, 85),      # S = 170 exactly
        (255, 170, 170),    # S = 85 exactly
        (32, 32, 32),       # L = 32 exactly, S=0
    ]
    rng = np.random.default_rng(seed=20260519)
    triples += [tuple(int(x) for x in rng.integers(0, 256, size=3)) for _ in range(17)]

    cases = []
    for (r, g, b) in triples:
        img = Image.new("RGB", (1, 1), (r, g, b))
        h, s, v = img.convert("HSV").getpixel((0, 0))
        cases.append({"rgb": [r, g, b], "hsv": [h, s, v]})
    return {"description": "RGB -> PIL 'HSV' uint8 channels. PIL uses INTEGER arithmetic; Math.round(float_hsv * 255) differs on .5 boundaries.",
            "boundary_examples_to_verify": [
                {"rgb": [100, 150, 200], "pil_hsv": [148, 127, 200], "naive_round": [149, 128, 200]}
            ],
            "cases": cases}


GENERATORS = {
    "grayscale_cases.json": gen_grayscale_cases,
    "hsv_cases.json":       gen_hsv_cases,
}


def atomic_write_json(path: Path, data: dict) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")
    tmp.replace(path)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    if args.check:
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            drift = []
            for name, gen in GENERATORS.items():
                generated = gen()
                committed = json.loads((SPEC_DIR / name).read_text())
                if committed != generated:
                    drift.append(name)
            if drift:
                print("Drift in unit cases:", drift, file=sys.stderr)
                return 1
        print("unit cases: no drift.")
        return 0

    for name, gen in GENERATORS.items():
        atomic_write_json(SPEC_DIR / name, gen())
        print(f"wrote {name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
