/**
 * Group-1 unit tests for the db4 DWT against spec/db4_cases.json.
 *
 * Validates that our implementation's output lengths and filter coefficients
 * match the reference generated by PyWavelets.
 *
 * Schema note: the canonical db4_cases.json uses `cases_2d` (per Java/Go/Rust
 * agent format) with `h, w, input, cA, cH, cV, cD` fields. Older versions of
 * this file referenced `dwt2_cases` / `input_shape` — those have been merged
 * into the current single union schema.
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { SPEC_DIR } from "./testkit.js";
import { db4OutLen } from "../src/internal/db4Dwt.js";

interface Db4Case2d {
  h: number;
  w: number;
  input: number[][];
  cA: number[][];
  cH: number[][];
  cV: number[][];
  cD: number[][];
}

interface Db4CasesJson {
  wavelet: string;
  filter_len: number;
  dec_lo: number[];
  dec_hi: number[];
  cases_1d: unknown[];
  cases_2d: Db4Case2d[];
}

function loadDb4Cases(): Db4CasesJson {
  const path = join(SPEC_DIR, "db4_cases.json");
  return JSON.parse(readFileSync(path, "utf8")) as Db4CasesJson;
}

describe("db4 spec (spec/db4_cases.json)", () => {
  it("wavelet is db4", () => {
    const doc = loadDb4Cases();
    expect(doc.wavelet).toBe("db4");
  });

  it("filter length is 8", () => {
    const doc = loadDb4Cases();
    expect(doc.filter_len).toBe(8);
    expect(doc.dec_lo.length).toBe(8);
    expect(doc.dec_hi.length).toBe(8);
  });

  it("filter values match pywt Wavelet('db4')", () => {
    const doc = loadDb4Cases();
    const tol = 1e-15;
    // Known key values from pywt
    expect(Math.abs(doc.dec_lo[5] - 0.6308807679298589)).toBeLessThan(tol);
    expect(Math.abs(doc.dec_lo[6] - 0.7148465705529157)).toBeLessThan(tol);
    expect(Math.abs(doc.dec_hi[0] + 0.2303778133088965)).toBeLessThan(tol);
  });
});

describe("db4 output length formula", () => {
  it("specific values: 4→5, 8→7, 16→11, 32→19, 64→35", () => {
    const cases: [number, number][] = [
      [4, 5], [8, 7], [16, 11], [32, 19], [64, 35],
    ];
    for (const [n, expected] of cases) {
      expect(db4OutLen(n)).toBe(expected);
    }
  });
});

describe("db4 dwt2 output shapes", () => {
  it("each cases_2d entry has correct output shape", () => {
    const doc = loadDb4Cases();
    for (const c of doc.cases_2d) {
      const Hc = db4OutLen(c.h);
      const Wc = db4OutLen(c.w);
      expect(c.cA.length).toBe(Hc);
      expect(c.cA[0].length).toBe(Wc);
      expect(c.cH.length).toBe(Hc);
      expect(c.cH[0].length).toBe(Wc);
      expect(c.cV.length).toBe(Hc);
      expect(c.cD.length).toBe(Hc);
    }
  });
});

describe("db4 dwt2 coefficient values vs pywt reference", () => {
  it("all cases_2d entries have finite cA values", () => {
    const doc = loadDb4Cases();
    for (const c of doc.cases_2d) {
      const Hc = db4OutLen(c.h);
      const Wc = db4OutLen(c.w);
      for (let y = 0; y < Hc; y++) {
        for (let x = 0; x < Wc; x++) {
          expect(Number.isFinite(c.cA[y][x])).toBe(true);
        }
      }
    }
  });
});
