"""Verify that rosetta_imagehash re-exports the upstream `imagehash` surface
correctly: each public function/class is importable, callable with the same
signature, and produces byte-exact output identical to calling `imagehash`
directly (since it IS the same function — these tests guard against
accidental wrapping or shadowing).

These also serve as a self-consistency check: running them against
spec/goldens.json proves the goldens were generated by the same upstream
version we're now re-exporting.
"""

from __future__ import annotations

import json
import struct
from pathlib import Path

import numpy as np
import pytest
from PIL import Image

import imagehash
import rosetta_imagehash as rih


REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SPEC = REPO_ROOT / "spec"
GOLDENS_PATH = SPEC / "goldens.json"
DECODED_DIR = SPEC / "decoded"
FIXTURES_DIR = SPEC / "fixtures"


def _load_goldens() -> dict:
    return json.loads(GOLDENS_PATH.read_text())


def _load_predecoded(fixture_name: str) -> Image.Image:
    path = DECODED_DIR / f"{fixture_name}.rgb.bin"
    blob = path.read_bytes()
    w, h = struct.unpack("<II", blob[:8])
    rgb = np.frombuffer(blob[8:], dtype=np.uint8).reshape((h, w, 3))
    return Image.fromarray(rgb, mode="RGB")


def _sized_cases(algo: str) -> list[tuple[str, int, str]]:
    g = _load_goldens()
    algo_entry = g["algorithms"][algo]
    out: list[tuple[str, int, str]] = []
    for fix, sizes in sorted(algo_entry["fixtures"].items()):
        for size_str, hex_str in sorted(sizes.items(), key=lambda kv: int(kv[0])):
            if hex_str is None:
                continue
            out.append((fix, int(size_str), hex_str))
    return out


# --- Re-export identity checks ---

def test_imagehash_version_matches_pin():
    """Detect upstream version drift early."""
    # Spec pins 4.3.2; allow any 4.3.x.
    assert imagehash.__version__.startswith("4.3."), imagehash.__version__


@pytest.mark.parametrize(
    "name",
    [
        "ImageHash",
        "ImageMultiHash",
        "hex_to_flathash",
        "hex_to_hash",
        "hex_to_multihash",
        "old_hex_to_hash",
    ],
)
def test_reexport_identity(name: str):
    """Each name on rih MUST be the same object as the one on imagehash —
    not a wrapper or alias. This list now only covers non-algorithm
    re-exports (hash classes, hex helpers). Every algorithm name (phash,
    phash_simple, whash_db4, whash_db4_robust, average_hash, dhash,
    dhash_vertical, whash, colorhash, crop_resistant_hash) is a port-local
    wrapper — see :func:`test_algorithm_override_is_not_upstream`."""
    assert getattr(rih, name) is getattr(imagehash, name), (
        f"{name}: rih.{name} is not imagehash.{name}"
    )


@pytest.mark.parametrize(
    "name",
    [
        # Snap-applying overrides (also composite RGBA)
        "phash",
        "phash_simple",
        "whash_db4",
        "whash_db4_robust",
        # RGBA-compositing overrides (forward to upstream after composite)
        "average_hash",
        "dhash",
        "dhash_vertical",
        "whash",
        "colorhash",
        "crop_resistant_hash",
    ],
)
def test_algorithm_override_is_not_upstream(name: str):
    """Every algorithm exposed on rih must be a port-local wrapper, NOT the
    upstream ``imagehash`` function. The snap-applying overrides apply
    SNAP_EPS / EPS; the rest apply the RGBA → RGB composite preamble. Both
    classes are necessary for cross-port byte-exact parity."""
    if hasattr(imagehash, name):
        assert getattr(rih, name) is not getattr(imagehash, name), (
            f"{name}: rih.{name} must be a port-local override, not the upstream function"
        )
    assert callable(getattr(rih, name))


def test_extension_constant_exposed():
    assert isinstance(rih.WHASH_DB4_ROBUST_EPS, float)
    assert rih.WHASH_DB4_ROBUST_EPS == 1e-12
    assert isinstance(rih.SNAP_EPS, float)
    assert rih.SNAP_EPS == 1e-10


def test_extension_function_exposed():
    assert callable(rih.whash_db4_robust)


# --- End-to-end byte-exact checks via re-exported functions ---

@pytest.mark.parametrize("fixture,size,expected_hex", _sized_cases("average_hash"),
                          ids=lambda v: str(v))
def test_reexport_average_hash_matches_goldens(fixture: str, size: int, expected_hex: str):
    """`rih.average_hash` must produce the same hex as the frozen golden."""
    img = _load_predecoded(fixture)
    h = rih.average_hash(img, hash_size=size)
    assert str(h) == expected_hex, (
        f"{fixture} size={size}: rih.average_hash diverged from imagehash 4.3.2 — "
        f"either upstream changed or the re-export is wrapped"
    )


@pytest.mark.parametrize("fixture,size,expected_hex", _sized_cases("phash"),
                          ids=lambda v: str(v))
def test_reexport_phash_matches_goldens(fixture: str, size: int, expected_hex: str):
    img = _load_predecoded(fixture)
    h = rih.phash(img, hash_size=size)
    assert str(h) == expected_hex


@pytest.mark.parametrize("fixture,size,expected_hex", _sized_cases("dhash"),
                          ids=lambda v: str(v))
def test_reexport_dhash_matches_goldens(fixture: str, size: int, expected_hex: str):
    img = _load_predecoded(fixture)
    h = rih.dhash(img, hash_size=size)
    assert str(h) == expected_hex


@pytest.mark.parametrize("fixture,size,expected_hex", _sized_cases("phash_simple"),
                          ids=lambda v: str(v))
def test_reexport_phash_simple_matches_goldens(fixture: str, size: int, expected_hex: str):
    img = _load_predecoded(fixture)
    h = rih.phash_simple(img, hash_size=size)
    assert str(h) == expected_hex


@pytest.mark.parametrize("fixture,size,expected_hex", _sized_cases("dhash_vertical"),
                          ids=lambda v: str(v))
def test_reexport_dhash_vertical_matches_goldens(fixture: str, size: int, expected_hex: str):
    img = _load_predecoded(fixture)
    h = rih.dhash_vertical(img, hash_size=size)
    assert str(h) == expected_hex


@pytest.mark.parametrize("fixture,size,expected_hex", _sized_cases("whash_haar"),
                          ids=lambda v: str(v))
def test_reexport_whash_haar_matches_goldens(fixture: str, size: int, expected_hex: str):
    img = _load_predecoded(fixture)
    h = rih.whash(img, hash_size=size, mode="haar", remove_max_haar_ll=True)
    assert str(h) == expected_hex


# --- crop_resistant_hash + ImageMultiHash via re-export ---

def _multihash_cases() -> list[tuple[str, str]]:
    g = _load_goldens()
    algo = g["algorithms"].get("crop_resistant_hash")
    if not algo:
        return []
    return [(fix, sizes["default"]) for fix, sizes in sorted(algo["fixtures"].items())]


@pytest.mark.parametrize("fixture,expected_hex", _multihash_cases(),
                          ids=lambda v: str(v))
def test_reexport_crop_resistant_hash_matches_goldens(fixture: str, expected_hex: str):
    """Verifies that imagehash.crop_resistant_hash via the re-export still
    produces what's in goldens.json. If this fails after an `imagehash`
    upgrade, the goldens are stale and need regeneration."""
    img = Image.open(FIXTURES_DIR / fixture)
    multihash = rih.crop_resistant_hash(img)
    assert str(multihash) == expected_hex


def test_imagemultihash_subtract_returns_float():
    """Documented invariant: ImageMultiHash distance is float, not int."""
    img = Image.open(FIXTURES_DIR / "peppers.png")
    a = rih.crop_resistant_hash(img)
    b = rih.crop_resistant_hash(img)
    d = a - b
    assert isinstance(d, float), f"distance is {type(d).__name__}, expected float"
    assert d == 0.0, "identical images should have distance 0.0"


def test_hex_to_multihash_round_trip():
    img = Image.open(FIXTURES_DIR / "peppers.png")
    mh = rih.crop_resistant_hash(img)
    s = str(mh)
    restored = rih.hex_to_multihash(s)
    assert str(restored) == s, "hex round-trip failed"
